# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
url     : https://ultraji.xyz
baseurl : 
title   : ultrajiのblog
description: > 
  操千曲而后晓声，观千剑而后识器

## => Language and Timezone
lang: zh
timezone: Asia/Shanghai

## => Author and Social
author:
  type      : person
  name      : Jack Wang
  url       : https://github.com/ultraji
  avatar    : /assets/mstile-150x150.png
  bio       : cloud computing software engineer
  email     : ultraji@live.com
  github    : ultraji


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: ultraji/ultraji.github.io
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: "h1,h2,h3"


## => Markdown Enhancements
##############################
## Mathjax
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: # false (default), true

## Chart
chart: # false (default), true

## => Paginate
##############################
paginate: 10
paginate_path: /page/:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg

## => Comments
##############################
giscus:
  repo:                "ultraji/ultraji.github.io"
  repo-id:             "MDEwOlJlcG9zaXRvcnkyMTQxODU5MTk="
  category:            "Announcements"
  category-id:         "DIC_kwDODMQ3v84CA-G3"
  mapping:             "pathname"
  reaction-enabled:    "1"
  theme:               "light"
  crossorigin:         "anonymous"

## => Search
##############################
search:
  provider: default # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: # Google Custom Search Engine ID


## => Analytics
analytics:
  google:
    tracking_id : G-NESVTLV2JY
    anonymize_ip: false # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      license: true
      aside:
        toc: true
      show_edit_on_github: true

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# deployment:
host: 0.0.0.0
